### ISSUE TITLE
USER STORY: Users can change their password

### ISSUE THREAD

**Issue by SerJosh** [SerJosh/wordsmith#11]
As a **User** I can **change my password** so that **I can keep my account secure**

## Acceptance Criteria

- Acceptance Criteria 1
**Given** that I am a registered User, logged in to my account
**When** I navigate to the edit profile page
**Then** I have the option to change my password
- Acceptance Criteria 2
**Given** that I am logged in to my account
**When** I change my password
**Then** I receive an email confirming my password has been changed
Acceptance Criteria 3
**Given** that I am logged into my account
**When** I click the change password link
**Then** I am taken to the change password form
**When** I correctly complete the form
And, press submit
**Then** My password is changed to the new value
And, I receive confirmation on the screen of the change.

## Tasks

- [ ] Task 1 - Develop a form for users to change their password
    
- [ ] Task 2 - Include a link to the form on the edit profile page to change password – this link should only be visible if the user is logged in
      
- [ ] Task 3 - Develop form validation to ensure that the password entered meets the requirements

- [ ] Task 4 - Develop a feedback notification mechanism to provide users with feedback on the successful, or failure of the password change

- [ ] Task 5 - Develop an automated email to the user providing additional confirmation that the password was successfully changed
