### ISSUE TITLE
USER STORY: Features restricted to signed in users

### ISSUE THREAD

**Issue by SerJosh** [SerJosh/wordsmith#13]
As a **Site Owner** I can **restrict some features of the site registered users have access to** so that **it encourages people to sign up to the site**

## Acceptance Criteria

- Acceptance Criteria 1
**Given** that a user is not registered or signed in,
**When** they want to create a short story
**Then** they do not have the ability to create a short story
- Acceptance Criteria 2
**Given** that a user is not registered or signed in,
**When** they view other short stories
**Then** they are unable to provide an upvote or comment
- Acceptance Criteria 3
**Given** that a user is not registered or signed in,
**When** they encounter functionality that requires them to be signed in
**Then** they are presented with a login or register button.

## Tasks

- [ ] task 1 - Develop restrictions to user access to create short story functionality
    
- [ ] task 2 - Develop restrictions to rating and comment functionality for non logged in users
      
- [ ] task 3 - For users who are not logged in, develop links so they can log in/register when an action requires a registered user, and are returned to their original place on the site. E.g. if they want to create a short story, but are not logged in, when they login, they are taken back to the short story.
