### ISSUE TITLE
USER STORY: Create a Short Story

### ISSUE THREAD

**Issue by SerJosh** [SerJosh/wordsmith#15]
As a **User** I can **create short stories** so that **I can enjoy writing and capture my own work on a platform**

## Acceptance Criteria

- Acceptance Criteria 1
**Given** that I am a logged in user
**When** I navigate to the create short story section
**Then** I have the option to create a short story
- Acceptance Criteria 2
**Given** that I have created a short story as a logged in user
**When** I save the completed short story
**Then** it is available to view  

## Tasks

- [ ] task 1 - Develop a model for a short story record
    
- [ ] task 2 - Connect the form to the short story model to create a new short story record
      
- [ ] task 3 - Develop the ability to create the record once the short story has been completed

- [ ] task 4 -  Develop validation for the short story form to ensure correct information is included
