### ISSUE TITLE
USER STORY: Edit a short story

### ISSUE THREAD

**Issue by SerJosh** [SerJosh/wordsmith#17]
As a **user** I can **edit a short story that I have created** so that **I can correct any mistakes I may have made, or add/improve it**

## Acceptance Criteria

- Acceptance Criteria 1
**Given** that I am a registered user who has created a short story
**When** I navigate to that short story
**Then** I have the option to edit the short story
- Acceptance Criteria 2
**Given** that I am a registered user who has created a short story
**When** I navigate to that short story, and click the option to edit the short story
**Then** I am able to edit the details of the short story
Acceptance Criteria 4
**Given** that I am a registered user who has created a short story
**When** I navigate to the short story, click the option to edit the details
And **When** I have edited the details of the short story
**Then** I have the option to save the changes

## Tasks

- [ ] task 1 - Develop an edit short story button for logged in users on the short story they have created
    
- [ ] task 2 - Develop an edit short story page that allows the user to edit the short story
      
- [ ] task 3 - Develop a save changes button to allow the user to save any changes they made to the short story.
