### ISSUE TITLE
USER STORY: Delete a Short Story

### ISSUE THREAD

**Issue by SerJosh** [SerJosh/wordsmith#18]
As a **user** I can **delete a short story that I have created** so that **I can remove it from the site**

## Acceptance Criteria

- Acceptance Criteria 1
**Given** that I am a registered user who is logged in, and has created a short story
**When** I navigate to the short story that I would like to delete
**Then** I have the option to delete the short story
- Acceptance Criteria 2
**Given** that I am a registered user who is logged in, has created a short story and I am viewing the short story I wish to delete
**When** I click the delete short story button
**Then** I receive a confirmation window to confirm that I really want to delete the short story
- Acceptance Criteria 3
**Given** that I am a registered user who is logged in, has created a short story, navigated to that short story and clicked on the delete short story button
**When** the confirmation window appears and I confirm the deletion
**Then** the short story is deleted from the system

## Tasks

- [ ] task 1 - Develop a delete short story button that appears on the short story page when the logged in user is the short story author
    
- [ ] task 2 - Develop a deletion confirmation window that appears when the user clicks the delete short story button
      
- [ ] task 3 - Develop the code that deletes the short story record when the user confirms the deletion, provided that the user requesting the deletion is the author
