### ISSUE TITLE
USER STORY: Django Setup

### ISSUE THREAD

**Issue by SerJosh** [SerJosh/wordsmith#2]
As a Developer, I want to set up Django and install the supporting libraries needed, so that I am ready to start development

## Tasks

- [ ] Task 1 -  Install Django
    
- [ ] Task 2 - Install dj_database_url psycopg2
      
- [ ] Task 3 - Create a requirements.txt file

- [ ] Task 4 - Create the Django project – called wordsmith

- [ ] Task 5 - Create the first app, called stories and add it to the installed apps in the settings.py

- [ ] Task 6 - Create new instance in Postgres SQL and connect database to code
