### ISSUE TITLE
USER STORY: Implementation of Responsive Design

### ISSUE THREAD

**Issue by SerJosh** [SerJosh/wordsmith#20]
As a **user** I can **easily navigate and view content** so that **I can use any device, no matter what the screen size**

## Acceptance Criteria

* Given that the user is visiting the site
  When the user is using a different device
  Then the website automatically adjusts its content to accommodate for the screen size

## Tasks

- [ ] task 1 - Use media queries to make content responsive up to 325px
    
- [ ] task 2 - when needed use bootstrap to make content responsive 
      
- [ ] task 3 - test responsive content on mobile phone
