### ISSUE TITLE
USER STORY: Utilise attractive fonts and colour scheme

### ISSUE THREAD

**Issue by SerJosh** [SerJosh/wordsmith#21]
As a **user** I can **visit a website that is enterprising and easy on the eye** so that **when I interact with the site, it is easy and enjoyable **

## Acceptance Criteria

* **Given** that the user visits the website 
  **When** the user sees the display of text and colour scheme
  **Then** the user will want to stay as the display is engaging, simplistic, creative and easy on the eye
  

## Tasks

- [ ] task 1 - choose fonts for headings and text that is original and easy to read
    
- [ ] task 2 - implement engaging background 
      
- [ ] task 3 - space content so it is easy to understand
