### ISSUE TITLE
USER STORY: Early Deployment to Heroku

### ISSUE THREAD

**Issue by SerJosh** [SerJosh/wordsmith#3]
As a Developer, I want to deploy the app to Heroku, so that I can confirm everything works before development of the site.

## Tasks

- [ ] Task 1 - Update code for deployment
    
- [ ] Task 2 - Create new Heroku app
      
- [ ] Task 3 - Connect Heroku to the PostgreSQL database

- [ ] Task 4 - Implement and add Secret Key to project and Heroku config vars
