### ISSUE TITLE
USER STORY: Create a User Account 

### ISSUE THREAD

**Issue by SerJosh** [SerJosh/wordsmith#5]
As a **user** I would like **to be able to create an account** so that **I can create and post short stories**

## Acceptance Criteria

- Acceptance Criteria 1
**Given** that I am an unregistered user
**When** I am on the homepage
**Then** I can see a button to sign up
And, **When** I click on the button
Then I am taken to the user registration page

- Acceptance Criteria 2
**Given** that I am an unregistered user
And, I am on the user registration page
**When** I enter my username, email address and password
And, I click on the register button
**Then** The system creates me an account
And, signs me in

- Acceptance Criteria 3
**Given** that I have an account
And, I am signed into the account
**When** I have an option to write a short story
And, when I click on that option
**Then** I am taken to a page where I can write my short story

- Acceptance Criteria 4
**Given** that I am a registered user
**When** I am signed into my account
**Then** I do not see the register button

## Tasks

- [ ] task 1 - Install AllAuth
    
- [ ] task 2 - Develop ability for users to register for a user account
      
- [ ] task 3 - Develop a  page and button in the nav bar to direct users to the registration page

- [ ] task 4 - Remove the register button from the nav bar when users are logged in

- [ ] task 5 - Create a User Registration form

- [ ] task 6 - Create a button in the home page to create a short story directing to a create short story page

## Epic: #4
