### ISSUE TITLE
USER STORY: Users must confirm their email

### ISSUE THREAD

**Issue by SerJosh** [SerJosh/wordsmith#6]
As a **developer** I can **make users confirm their email** so that **I can keep my account secure**

## Acceptance Criteria

- Acceptance Criteria 1
**Given** that a user wants to register
**When** they fill in the details in the registration page
**Then** they have to confirm their email
- Acceptance Criteria 2
Given that the user has confirmed their email
When they have confirmed it in their email
Then they will be able to access the site as a registered user

## Tasks

- [ ] Task 1 - Develop an automated email platform for users to receive email confirmations 
    
- [ ] Task 2 - Include a link to the website to go back once they have confirmed
      
- [ ] Task 3 - Develop the ability to see confirmed users in the admin page
