### ISSUE TITLE
USER STORY: Users can edit their profile

### ISSUE THREAD

**Issue by SerJosh** [SerJosh/wordsmith#9]
As a **User** I can ** edit my profile** so that **I can change my details to what I want**

## Acceptance Criteria

- Acceptance Criteria 1
**Given** that I am logged into my account
**When** I am viewing my profile
**Then** I should be able to edit the details
- Acceptance Criteria 2
**Given** that I am logged into my account
**When** I click on the edit button on my profile page
**Then** I should be taken to a page to edit the details
- Acceptance Criteria 3
**Given** that I am not logged into my account
**When** I view my profile page, or anyone elses
**Then** I should not be able to see any user profile button

## Tasks

- [ ] Task 1 - Develop the ability for users to edit their own profile
    
- [ ] Task 2 - Develop a page where users can edit the information within their profile
      
- [ ] Task 3 - Add a button to a users profile that only displays when they are logged in and viewing their own profile

- [ ] Task 4 - Prevent users accessing any form of editing an account
